name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Build Project
        run: ./gradlew build --stacktrace
